#!/usr/bin/env node
'use strict'

const program = require('commander');

program
  .name('reactance')
  .version(require(`${__dirname}/package.json`).version, '-v, --version');

program
  .command('new <app_name>')
  .alias('n')
  .description('create a new app of react & redux')
  .option('-a, --author <author>', 'add author')
  .option('-m, --minimum', 'create a minimum app of react')
  .action((app_name, options) => {
    require('./create-react-custom-app')(app_name, options.author, options.minimum);
  });

program
  .command('reducer <reducer_name>')
  .alias('r')
  .description('create a new reducer of react & redux')
  .option('-m, --minimum', 'create a minimum reducer')
  .action((reducer_name) => {
    require('./create-actions-reducer')(reducer_name);
  });

program
  .command('component <component_name>')
  .alias('c')
  .description('create a new component of react & redux')
  .action((component_name) => {
    require('./create-component-container')(component_name);
  });

program.parse(process.argv);
